name: schedule

on:
  schedule:
    - cron: "0/1 * * * *"
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup environment
        run: |
          echo "DAY=$(date -u '+%Y-%m-%d')" >> $GITHUB_ENV
          mkdir -p data/github/$DAY
          mkdir -p data/github/$DAY/readmes
          
      - name: Fetch GitHub repositories
        run: |
          for days in 1 3 7; do
            file="data/github/$DAY/repo_${days}d_stars.json"
            created_filter="created:>$(date -u -d "$days days ago" '+%Y-%m-%d')"
            temp_file=$(mktemp)
            
            page=1
            while [[ $page -le 100 ]]; do
              curl -sS -G "https://api.github.com/search/repositories" \
                --data-urlencode "sort=stars" \
                --data-urlencode "q=$created_filter" \
                --data-urlencode "page=$page" \
                --data-urlencode "per_page=100" >> "$temp_file"
              ((page++))
            done
            
            jq '.items' "$temp_file" > "$file"
            rm "$temp_file"
          done

      - name: Validate JSON
        run: |
          for days in 1 3 7; do
            file="data/github/$DAY/repo_${days}d_stars.json"
            if ! jq empty "$file"; then
              echo "Invalid JSON: $file"
              exit 1
            fi
          done

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub data for ${{ env.DAY }}"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@users.noreply.github.com"

      - name: Notify on failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚨 Workflow failed! ${{ github.workflow }}"
            })
